#!/usr/bin/python3
from SinCity.colors import BLUE, RESET, RED, GREEN
from SinCity.Scanners.scanner_wp_plugin import Scanner
from __init__ import __author__, __version__

import textwrap

def inDev():
    """Просто обозначим, что модуль в процессе разработки"""
    text = f'{RED}Модуль в процессе разработки...{RESET}'
    print(text) 

def menuScanner():
    menu = f"""\
    +--------------------------------------------------
    | Snanner Sin
    +--------------------------------------------------
    | Version: \t{__version__}
    | Author: \t{__author__}
    +--------------------------------------------------
    | [+] Сканнер возможножных страниц              [1]
    | [+] Сканнер поддоменов                        [2]
    | [+] Проверить Whois                           [4]
    |       
    | [ ] WordPress
    | [+] Сканнер плагинов                          [5]
    +--------------------------------------------------
    """
    menu = textwrap.dedent(menu)
    select_point = input(
            f'{GREEN}{menu}{RESET}'
            f'{RED}>>> {RESET}'
            )
    if int(select_point) == 1:inDev()
    if int(select_point) == 2:inDev()
    if int(select_point) == 3:inDev()
    if int(select_point) == 5:Scanner()

if __name__ == '__main__':
    try:
        menuScanner()
    except KeyboardInterrupt:
        print(f'{RED}\nBye bye{RESET}')

